namespace ATS {
namespace ELM {

enum class VarID : int {
    BASE_POROSITY,
    HYDRAULIC_CONDUCTIVITY,
    CLAPP_HORBERGER_B,
    CLAPP_HORBERGER_PSI_SAT,
    RESIDUAL_SATURATION,
    EFFECTIVE_POROSITY,
    ROOT_FRACTION,
    SURFACE_WATER_CONTENT,
    WATER_CONTENT,
    PRESSURE,
    SURFACE_WATER_SOURCE,
    POTENTIAL_EVAPORATION,
    POTENTIAL_TRANSPIRATION,
    EVAPORATION,
    TRANSPIRATION,
    RUNOFF,
    BASEFLOW,
    ELEVATION,
};


} // namespace ELM
} // namespace ATS
