namespace ATS {
namespace ELM {

enum class VarID : int {
  NO_VARIABLE = 0,
  BASE_POROSITY = 1,
  HYDRAULIC_CONDUCTIVITY = 2,
  CLAPP_HORNBERGER_B = 3,
  CLAPP_HORNBERGER_PSI_SAT = 4,
  RESIDUAL_SATURATION = 5,
  EFFECTIVE_POROSITY = 6,
  ROOT_FRACTION = 7,
  SURFACE_WATER_CONTENT = 8,
  WATER_CONTENT = 9,
  PRESSURE = 10,
  GROSS_SURFACE_WATER_SOURCE = 11,
  POTENTIAL_EVAPORATION = 12,
  POTENTIAL_TRANSPIRATION = 13,
  EVAPORATION = 14,
  TRANSPIRATION = 15,
  RUNOFF = 16,
  BASEFLOW = 17,
  ELEVATION = 18,
  TIME = 19,
  INITIAL_WATER_CONTENT = 20,
  SATURATION_LIQUID = 21,
  PONDED_DEPTH = 22
};

} // namespace ELM
} // namespace ATS
